### ISSUE TITLE
QuickCost webservice is used even if disable 

### ISSUE THREAD

**Issue by vberthet** [PrestaShop/chronopost#15]
QuickCost webservice is called even if it's disabled in module configuration.

Call graph for "getOrderShippingCost" when enabled :
![chrono_with_quickcost](https://cloud.githubusercontent.com/assets/1115715/8131452/a00f2730-111a-11e5-887a-3ed026a7e64c.jpg)

Call graph for "getOrderShippingCost" when disabled :
![chrono_no_quickcost](https://cloud.githubusercontent.com/assets/1115715/8131549/41e32ad4-111b-11e5-952e-f03fbbd58d3c.jpg)

The method "QuickcostServiceWSService->calculate" is called in both case.

**Comment by francoisfeugeas** [comment]
Hello @vberthet 

This behaviour is intended, QuickcostServiceWSService->calculate is used to check the availability of the Chrono10 and ChronoClassic services.

**Comment by vberthet** [comment]
Hi @francoisfeugeas 

My major problem is time spent in this function. If you take a look on graph, you can see global time spent in each function (approx 7s in "QuickcostServiceWSService->calculate").

I've done a small inspection to understand what's append. 

Chronopost webservice take approximately 200ms for each call (from my dev station with ADSL) wich is acceptable. Except that the method "Chronopost->getOrderShippingCost" is called ~13 time on each page load (when cart is not empty) that means php spend ~2.6s querying chronopost on each page load.

**Comment by francoisfeugeas** [comment]
Hello @berthet

I think the caching issue you're referring to has been fixed in my latest PR. 

Can you check and get back to me ?

Thank you

**Comment by vberthet** [comment]
Hi @francoisfeugeas

Your pull request fix my issue?

Thank you

**Comment by Quetzacoalt91** [comment]
Thanks @francoisfeugeas,

I close this issue.
