### ISSUE TITLE
OPC template not available

### ISSUE THREAD

**Issue by jeromenadaud** [PrestaShop/chronopost#17]
Please see screenshot taken on a site with One Page Checkout:

![screenshot 2015-07-29 14 30 04](https://cloud.githubusercontent.com/assets/4747745/8957409/9d28d49a-35fe-11e5-939e-ab261ad8d76d.png)

**Comment by francoisfeugeas** [comment]
Hello @jeromenadaud,

I'm not sure what you're referring to - our module uses the same template file for both OPC and 5-steps order methods as we're only adding one `<div>` to the page. 

Are you sure this is related to our module ?

Thank you

**Comment by jeromenadaud** [comment]
OK, sorry my bad, it's related to my theme.

Best regards
