### ISSUE TITLE
Sender's phone doesn't appear

### ISSUE THREAD

**Issue by Klemart3D** [PrestaShop/chronopost#21]
I registered a phone number in "Sender Informations" of module setting, but when I'm editing a new Chronopost slip, the phone number doesn't appear in the pdf file on "e-chronopass" page under chronopost logo (please see attachment).

Is it a general bug or only for me ?

![chronopost-phone-sender](https://cloud.githubusercontent.com/assets/7419525/9763860/0ffd1606-570c-11e5-9a51-05de05a59853.jpg)

**Comment by francoisfeugeas** [comment]
Good catch thank you !
Fixed in #26
