### ISSUE TITLE
Change "Solution PrestaShop" for shop's name

### ISSUE THREAD

**Issue by Klemart3D** [PrestaShop/chronopost#24]
On tracking page of Chronopost website, is there a way to change the "Solution Prestashop" event expeditor for the name of the shop for example ? (cf picture) The customer does'nt care whose ecommerce solution edits LT.

![solution-prestashop-chonopost](https://cloud.githubusercontent.com/assets/7419525/10043776/ec604f3e-61f5-11e5-9be4-1326ec84f347.jpg)

**Comment by francoisfeugeas** [comment]
Hello @Klemart3d

Unfortunately this is out of our area of control but I  transmitted your query to the relevant team 

Cordialement 
François Feugeas 

Oxileo 


---- Klemart3D a écrit ----

**Comment by francoisfeugeas** [comment]
@Klemart3D Chronopost's teams won't fix this, this is the same format used accross all modules and printing terminals.

**Comment by Klemart3D** [comment]
@francoisfeugeas Well, thank you for your inquiry;) Not solved, but if it can't be, I close this issue.
