### ISSUE TITLE
Chrono Classique & Express display only when is free

### ISSUE THREAD

**Issue by laurent-d** [PrestaShop/chronopost#37]
Hi,

On a fresh install prestashop 1.6.1.4
I have some issue to display Chrono Classique & Chrono Express on Front (for client) if these carriers are not setted free on Back.

The console shows just :
Google Maps API warning: NoApiKeys https://developers.google.com/maps/documentation/javascript/error-messages#no-api-keys
util.js:212 Google Maps API warning: SensorNotRequired https://developers.google.com/maps/documentation/javascript/error-messages#sensor-not-required

This behaviour is normal ?

Many thanks

**Comment by francoisfeugeas** [comment]
Hi,

Yes this behaviour is normal as the Google Map is included for ChronoRelais
They are merely warning messages from the Google Maps library and have no bearing on the funcitonnality of the module.

**Comment by laurent-d** [comment]
Thanks for you reply François,

But the main issue is the impossibility of offering  Chrono Classic & Chrono Express not freely. 
Please find attached the screen shot, Free Chrono express is display but the Classic do not.

![ps-bug](https://cloud.githubusercontent.com/assets/6553086/15777880/f5d32d2e-2992-11e6-892c-29b47aec2c56.jpg)

**Comment by francoisfeugeas** [comment]
ChronoClassic availability is dependent on the shipping route : address of origin + the destination country + destination postcode. The pricing of the carrier does not have any impact. 

The module does a webservice call to check the availability of the service... Did you check with Chronopost's support if the service should work for the route you're testing with ? 

Did you try activating QuickCost to see if that has any impact ?

**Comment by laurent-d** [comment]
Yes, i allready QuickCost activated (no errors in console nor with debugmode on)
And the route is from the same country and the same city (Paris/France).
Chronopost services have verified all settings.
I Have the same issue with express, classique and international express delivery before 18h..

Only these chronopost carriers work well :
Chronopost - Livraison express en point relais avant 13 h
Chronopost - Livraison express à domicile avant 13h
Chronopost - Livraison express à domicile avant 10h 

Do you have an idea ?

**Comment by francoisfeugeas** [comment]
Not sure that I'm understanding the issue at hand correctly here, but it looks like a configuration issue, either on your end or on Chronopost's end. 

ChronoExpress and ChronoClassic should never be displayed in a route to France - it's an international product. 

Can you drop an email @ support@oxileo.eu quoting your Chronopost issue number (numéro de dossier) so we look into it further ?

Thanks

**Comment by laurent-d** [comment]
Many thanks François for your support ! I will email as soon as possible
Kind regards
