### ISSUE TITLE
Marketing content

### ISSUE THREAD

**Issue by Quetzacoalt91** [PrestaShop/chronopost#5]
While I'm waiting for the credentials of a test account, can you please add a marketing content at the top of the settings page ?

It is always useful for the merchant to know what the module can do, how he can configure it etc.

BTW, how the *Customer informations* could be used ? All the shipments will be sent to the same address ?

**Comment by francoisfeugeas** [comment]
@Quetzacoalt91 can we close this issue ? Is this OK for you ?

**Comment by Quetzacoalt91** [comment]
Sure we can !
